#!/bin/bash
set -euo pipefail

# Deterministic Test Execution Script
# Generates comprehensive evidence of test execution

TIMESTAMP=$(date +%Y%m%d-%H%M%S)
RUN_ID="deterministic_run_${TIMESTAMP}"
RESULTS_DIR="test-evidence/${RUN_ID}"

echo "=========================================="
echo "🔬 DETERMINISTIC TEST EXECUTION"
echo "=========================================="
echo "Run ID: ${RUN_ID}"
echo "Timestamp: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
echo "Working Directory: $(pwd)"
echo "Node Version: $(node --version)"
echo ""

# Create results directory
mkdir -p "${RESULTS_DIR}"

# Save environment info
cat > "${RESULTS_DIR}/environment.json" <<EOF
{
  "runId": "${RUN_ID}",
  "timestamp": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
  "node": "$(node --version)",
  "npm": "$(npm --version)",
  "platform": "$(uname -s)",
  "arch": "$(uname -m)",
  "cwd": "$(pwd)"
}
EOF

# Function to run test phase
run_test_phase() {
  local phase_name=$1
  local command=$2
  local output_file="${RESULTS_DIR}/${phase_name}.log"
  local json_file="${RESULTS_DIR}/${phase_name}.json"
  
  echo ""
  echo "🏃 Running ${phase_name}..."
  echo "Command: ${command}"
  
  # Run test and capture output
  if $command > "${output_file}" 2>&1; then
    echo "✅ ${phase_name} completed successfully"
    echo "PASS" > "${RESULTS_DIR}/${phase_name}.status"
  else
    echo "❌ ${phase_name} failed"
    echo "FAIL" > "${RESULTS_DIR}/${phase_name}.status"
  fi
  
  # Extract metrics from output
  tail -50 "${output_file}" | grep -E "(Test Files|Tests|Duration)" || true
}

# Phase 1: Unit Tests
echo ""
echo "=== PHASE 1: UNIT TESTS ==="
run_test_phase "unit-tests" "pnpm test:run --reporter=default"

# Phase 2: Integration Tests  
echo ""
echo "=== PHASE 2: INTEGRATION TESTS ==="
run_test_phase "integration-tests" "pnpm test:run __tests__/integration --reporter=default"

# Phase 3: E2E Tests
echo ""
echo "=== PHASE 3: E2E TESTS ==="
run_test_phase "e2e-tests" "pnpm test:e2e --reporter=list || true"

# Phase 4: Coverage Report
echo ""
echo "=== PHASE 4: COVERAGE ANALYSIS ==="
if pnpm test:coverage --reporter=json > "${RESULTS_DIR}/coverage.json" 2>&1; then
  echo "✅ Coverage report generated"
  
  # Extract coverage summary
  if [ -f "coverage/coverage-summary.json" ]; then
    cp coverage/coverage-summary.json "${RESULTS_DIR}/coverage-summary.json"
    
    # Parse and display coverage
    node -e "
      const coverage = require('${RESULTS_DIR}/coverage-summary.json');
      const total = coverage.total;
      console.log('Coverage Summary:');
      console.log('  Lines:', total.lines.pct + '%');
      console.log('  Statements:', total.statements.pct + '%');
      console.log('  Functions:', total.functions.pct + '%');
      console.log('  Branches:', total.branches.pct + '%');
    " || echo "Could not parse coverage data"
  fi
else
  echo "⚠️  Coverage generation failed"
fi

# Generate final summary
echo ""
echo "=== GENERATING EVIDENCE SUMMARY ==="

cat > "${RESULTS_DIR}/summary.md" <<EOF
# Deterministic Test Evidence Report

## Execution Metadata
- **Run ID**: ${RUN_ID}
- **Timestamp**: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
- **Platform**: $(uname -s) ($(uname -m))
- **Node Version**: $(node --version)

## Test Results

### Unit Tests
- Status: $(cat ${RESULTS_DIR}/unit-tests.status 2>/dev/null || echo "N/A")
- Log: ${RUN_ID}/unit-tests.log

### Integration Tests  
- Status: $(cat ${RESULTS_DIR}/integration-tests.status 2>/dev/null || echo "N/A")
- Log: ${RUN_ID}/integration-tests.log

### E2E Tests
- Status: $(cat ${RESULTS_DIR}/e2e-tests.status 2>/dev/null || echo "N/A")
- Log: ${RUN_ID}/e2e-tests.log

### Coverage
- Report: ${RUN_ID}/coverage-summary.json

## Artifacts
All test artifacts are stored in: test-evidence/${RUN_ID}/

---
Generated by Deterministic Test Runner
EOF

# Display final summary
echo ""
echo "=========================================="
echo "📊 TEST EXECUTION COMPLETE"
echo "=========================================="
echo "Results saved to: ${RESULTS_DIR}"
echo ""
ls -la "${RESULTS_DIR}"
echo ""
echo "To view detailed results:"
echo "  cat ${RESULTS_DIR}/summary.md"
echo "=========================================="